### ISSUE TITLE
failed to run custom build command for `x11 v2.19.1`

### ISSUE THREAD

**Issue by hellowrldsa** [KunalBagaria/rustyvibes#18]
I get this error when I install it on ubuntu I googled found nothing.
I have libx11-dev and everything installed.

**Comment by GNVageesh** [comment]
Hello,

Maybe try installing the `libxss-dev` library by running `sudo apt-get install libxss-dev`

**Comment by KunalBagaria** [comment]
Thanks Vageesh 👍

**Comment by KunalBagaria** [comment]
You can try this as well:
```
sudo apt install libx11-dev
```
