### ISSUE TITLE
Failed to install rustyvibes

### ISSUE THREAD

**Issue by XCarCedo** [KunalBagaria/rustyvibes#27]
Hi, i just tried installing rustyvibes using `cargo install rustyibes` on windows and got tons of errors
The issue seems like to be coming from link.exe returning the error code of 1181
[pastebin](https://pastebin.com/L12XrA2c)

**Comment by XCarCedo** [comment]
So, i managed to fix the issue
seems like the problem was that rust msvc compiler required at least visual studio 2013 (visual studio is required for c++ build tools and windows 10 sdk though i'm not sure 2013 will work or not) and i had visual studio 2012, i tried to switch to gnu compiler but there was also compiling problems so i just uninstalled visual studio 2012 and installed 2022 with CMake, build tools, win10 sdk and switched back to the msvc compiler, rustyvibes seems to work just fine now

**Comment by KunalBagaria** [comment]
glad to hear, I'm actually not maintaining this project anymore, so appreciate you posting your fix here :)
